spring:
  application:
    name: Guidely

  datasource:
    url: jdbc:postgresql://localhost:5434/guidely
    username: guidely
    password: guidely
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  liquibase:
    change-log: db/changelog/master.yaml
    enabled: true

  docker:
    compose:
      file: src/main/docker/compose.yml
      enabled: true
      lifecycle-management: start_only



server:
  port: 4040

# ==================
# JWT Configuration
# ==================
jwt:
  secret: Wdx7ZeyAoF1pZ4R7Ksc5q9ut03Hw3HYyqN3Ei2Ly+H7zXLP44xZQwp65wwroBO3S
  access:
    expiration: 900000
  refresh:
    expiration: 7200000