spring:
  application:
    name: Guidely

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgresSQLDialect

  liquibase:
    change-log: db/changelog/master.yaml

  docker:
    compose:
      file: src/main/docker/compose.yml
      enabled: true
      lifecycle-management: start_only