version: "3.8"
name: guidely
services:
  postgresql:
    image: postgres:16.1
    environment:
      - POSTGRES_USER=guidely
      - POSTGRES_PASSWORD=guidely
      - POSTGRES_HOST_AUTH_METHOD=trust
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U $${POSTGRES_USER}']
      interval: 5s
      timeout: 5s
      retries: 10
    ports:
      - "127.0.0.1:5434:5432"
    networks:
      - guidely-net

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq_guidely_main
    ports:
      - "5672:5672"     # AMQP port
      - "15672:15672"   # Management UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - guidely-net

  sonar-postgres:
    image: postgres:latest
    container_name: sonar-postgres
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
      - POSTGRES_DB=sonar
    ports:
      - "5433:5432"
    networks:
      - guidely-net

  sonarqube:
    image: sonarqube:latest
    container_name: sonarqube
    environment:
      - SONAR_QUIET=true
    ports:
      - "9000:9000"
    depends_on:
      - sonar-postgres
    networks:
      - guidely-net

volumes:
  rabbitmq_data:

networks:
  guidely-net:
    driver: bridge
